### PR TITLE
Remove the need for storing the callbackStack in image

### PR DESCRIPTION
**Pull request by akgrant43**
The current architecture stores two copies of the callbackStack, one in the plugin and the other in-image.  If a callback return interrupts the sequence of starting another callback and updating the callbackStack the callback return will fail as the top entry of the two stacks is not the same.

This PR:

- modifies primitiveCallbackReturn() so that it returns specific error codes in the event the callbackStack is empty or the supplied callback isn't on the top of the stack, removing the need to keep a copy of the stack in-image.
- modifies TFRunner to remove the in-image stack and mutual exclusion semaphore and use the additional information returned by the primitive.

### CODE REVIEW

**Comment by tesonep** [comment]
Hi @akgrant43, the idea behind having in the image side was to correctly show information to the users of TFFI, and the idea of having on the plugin side is to avoid crashes. 
So that is the rationale behind having it duplicated. 

The problem in the image side was a bad architectural decision that I have taken. Even Esteban didn't like it in the moment. Previously the TFSameThreadWorker was a stateless object, so it was possible to create a new instance every time. However, when we changed to a stateful object, having the collection of callback activations the instances should be correctly shared, there should be only one instance in the image.

So, I will like not to remove the image collection of callbacks so it allows us to have a better error reporting (that is kind of missing also), but as it is a problem that maybe users of FFI (the ones implementing bindings) encounters the errors should be reported nice.

**Comment by akgrant43** [comment]
Hi Pablo,

How about adding the primitives necessary to access the callbackStack from the image?  That way we can still produce better error information and still remove the synchronisation problem.

I started to do this with `primitiveCallbackStackSize()`.  Being able to return the entries should be straight-forward.

**Comment by tesonep** [comment]
That can be a nice alternative, the other alternative is only to keep
the one in the image, if the image side works fine it should not crash
and it is easier to debug and develop.

On Tue, Dec 10, 2019 at 10:19 AM Alistair Grant
<notifications@github.com> wrote:
>
> Hi Pablo,
>
> How about adding the primitives necessary to access the callbackStack from the image? That way we can still produce better error information and still remove the synchronisation problem.
>
> I started to do this with primitiveCallbackStackSize(). Being able to return the entries should be straight-forward.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Pablo Tesone.
tesonep@gmail.com

**Comment by akgrant43** [comment]
> the other alternative is only to keep the one in the image

I like the idea.  My concern is that when a callback is made we can't be sure of the state of all the processes in the image.  I think it will always be possible that another process will be attempting to access or modify the in image callback stack before the current callback updates the stack, leaving the primitive with the possibility of returning out of order.

> if the image side works fine it should not crash and it is easier to debug and develop.

The difficulty is in addition to ensuring that only one process accesses the callbackStack at a time (which the mutual exclusion semaphore handles), we also need to ensure that the modifications are done in the correct order.  With a multiple processes running at potentially different priorities that becomes too hard.

**Pull request closed without merging**
